# 언어
language: java

# java developer kit version
jdk:
  - openjdk8

# 어떤 git branch 에 push되면 작동할 것인가?
branches:
  only:
    - master

# gradle 권한주기
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.gradle"

before_script:
  - chmod +x gradlew

# script는 gradlew clean build 실행된다
script:
  - ./gradlew clean build

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - kyungsik0907@gmail.com
