language: java
jdk:
- openjdk11
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_1116e8e6e492_key -iv $encrypted_1116e8e6e492_iv
  -in application.yml.enc -out application.yml -d
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
before_script:
- chmod +x gradlew
script:
- "./gradlew clean build"
notifications:
  email:
    recipients:
    - kyungsik0907@gmail.com
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-deploy-bucket # aws에서 생성한 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: kschoi93/spring-jpa-mysql-aws
      branch: master
