spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hello?serverTimezone=UTC&characterEncoding=UTF-8
    username: kschoi
    password: qlalfqjsgh1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
